project:
  type: website
  output-dir: docs

website:
  title: "RomuAnalyst"
  navbar:
    right:
      - text: "{{< fa paper-plane >}} Envoi TP"
        href: mailto:romuald.zami@u-paris.fr
format:
  html:
    theme: spacelab
    css: styles.css

editor: visual

